apiVersion: apps/v1
kind: Deployment
metadata:
  name: webhook-server-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: webhook-server
  template:
    metadata:
      labels:
        app: webhook-server
    spec:
      containers:
      - name: webhook-server
        image: syednadeembe/admission_controller:latest
        ports:
        - containerPort: 8080

